import { useEffect,useMemo,useRef,useState } from "react";
import { pick,type AdminLocale } from "../../localization/admin-translations";
import { categoryLabels,contextActionIds,getQuickActionContext,quickActions,type QuickAction } from "../../navigation/quick-actions";
export default function QuickActionsHub({activeId,locale,onNavigate}:{activeId:string;locale:AdminLocale;onNavigate:(id:string)=>void}){const [open,setOpen]=useState(false),[expanded,setExpanded]=useState(false),[query,setQuery]=useState("");const fabRef=useRef<HTMLButtonElement>(null),dialogRef=useRef<HTMLDivElement>(null);const context=getQuickActionContext(activeId);const primary=useMemo(()=>contextActionIds[context].map(id=>quickActions.find(x=>x.id===id)).filter(Boolean) as QuickAction[],[context]);const visible=expanded?quickActions.filter(x=>`${x.label.ar} ${x.label.en}`.toLowerCase().includes(query.trim().toLowerCase())):primary;const close=(restore=true)=>{setOpen(false);setExpanded(false);setQuery("");if(restore)requestAnimationFrame(()=>fabRef.current?.focus())};const select=(x:QuickAction)=>{onNavigate(x.target);close()};
useEffect(()=>{const key=(e:KeyboardEvent)=>{const typing=(e.target as HTMLElement).matches("input,textarea,[contenteditable=true]");if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"&&!typing){e.preventDefault();setOpen(v=>!v)}else if(e.key==="Escape"&&open){e.preventDefault();close()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open]);
useEffect(()=>{if(!open)return;const id=requestAnimationFrame(()=>dialogRef.current?.querySelector<HTMLElement>("input,button")?.focus());return()=>cancelAnimationFrame(id)},[open,expanded]);
useEffect(()=>{if(!open)return;const trap=(e:KeyboardEvent)=>{if(e.key!=="Tab"||!dialogRef.current)return;const n=[...dialogRef.current.querySelectorAll<HTMLElement>("button,input")];if(!n.length)return;const first=n[0],last=n[n.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener("keydown",trap);return()=>document.removeEventListener("keydown",trap)},[open,expanded,visible.length]);
const content=<div ref={dialogRef} id="quick-actions-dialog" className={`quick-actions-card ${expanded?"is-expanded":""}`} role="dialog" aria-modal="true" aria-label={locale==="ar"?"العمليات السريعة":"Quick Actions"}><div className="quick-actions-handle"/><header><div><span>{locale==="ar"?"مركز الاختصارات":"Shortcut hub"}</span><h2>{locale==="ar"?"العمليات السريعة":"Quick Actions"}</h2></div><kbd>⌘ / Ctrl K</kbd></header>{expanded&&<label className="quick-actions-search"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==="ar"?"ابحث عن عملية...":"Search actions..."}/></label>}{expanded?[...new Set(visible.map(x=>x.category))].map(category=><section className="quick-actions-group" key={category}><h3>{pick(categoryLabels[category],locale)}</h3><div className="quick-actions-grid">{visible.filter(x=>x.category===category).map(x=><Action item={x} locale={locale} onSelect={select} key={x.id}/>)}</div></section>):<div className="quick-actions-grid">{visible.map(x=><Action item={x} locale={locale} onSelect={select} key={x.id}/>)}</div>}{expanded&&visible.length===0&&<p className="quick-actions-empty">{locale==="ar"?"لا توجد عمليات مطابقة.":"No matching actions."}</p>}<footer><button type="button" onClick={()=>{setExpanded(v=>!v);setQuery("")}}>{expanded?(locale==="ar"?"عرض العمليات المقترحة":"Show Suggested"):(locale==="ar"?"عرض كل العمليات":"View All Actions")}</button><button type="button" onClick={()=>close()}>{locale==="ar"?"إغلاق":"Close"}</button></footer></div>;
return <><button ref={fabRef} type="button" className={`quick-actions-fab ${open?"is-open":""}`} aria-label={open?(locale==="ar"?"إغلاق العمليات السريعة":"Close quick actions"):(locale==="ar"?"فتح العمليات السريعة":"Open quick actions")} aria-expanded={open} aria-controls="quick-actions-dialog" onClick={()=>open?close(false):setOpen(true)}><span>＋</span></button>{open&&<div className="quick-actions-layer"><button className="quick-actions-backdrop" type="button" aria-label={locale==="ar"?"إغلاق":"Close"} onClick={()=>close()}/>{content}</div>}</>}
function Action({item,locale,onSelect}:{item:QuickAction;locale:AdminLocale;onSelect:(x:QuickAction)=>void}){return <button className={`quick-action-item ${item.ai?"is-ai":""}`} type="button" onClick={()=>onSelect(item)}><i>{item.icon}</i><span><strong>{pick(item.label,locale)}</strong><small>{pick(item.description,locale)}</small></span>{item.ai&&<b>AI</b>}</button>}
