import { homeCategories, homeProducts, paymentMethods, quickActions } from "../../data/home-data";
import { navigate } from "../../hooks/useRoute";
import { useStorefront } from "../../hooks/useStorefront";
import type { HomeProduct } from "../../types/home";
import { money, t } from "../../utils/i18n";
import { Icon } from "../ui/Icon";

export function HomeGreeting(){const{locale,state}=useStorefront();const hour=new Date().getHours();return <section className="home-greeting"><div><span>{hour<12?(locale==="ar"?"صباح الخير":"Good morning"):(locale==="ar"?"مساء الخير":"Good evening")}</span><h2>{locale==="ar"?"مرحبًا، جون":"Welcome, John"}</h2><p>{locale==="ar"?"كل ما تحتاجه لإدارة مشترياتك الرقمية، في لمحة واحدة.":"Everything you need for your digital purchases, at a glance."}</p></div><div className="greeting-stats"><span><small>{locale==="ar"?"الرصيد":"Balance"}</small><strong>{money(state.balance,locale)}</strong></span><span><small>{locale==="ar"?"الطلبات":"Orders"}</small><strong>{state.orders.length}</strong></span><span><small>{locale==="ar"?"قيد التنفيذ":"Pending"}</small><strong>{state.orders.filter(order=>order.status==="processing"||order.status==="pending").length}</strong></span></div><div><button className="home-button primary" onClick={()=>navigate("/wallet/deposit")}>{locale==="ar"?"إضافة رصيد":"Add funds"}</button><button className="home-button ghost" onClick={()=>navigate("/orders")}>{locale==="ar"?"عرض الطلبات":"View orders"}</button></div></section>}
export function HomeQuickActions(){const{locale}=useStorefront();return <section className="home-section compact"><HomeHeading title={locale==="ar"?"اختصاراتك":"Quick actions"} subtitle={locale==="ar"?"طرق أسرع للوصول إلى ما تحتاجه":"Faster ways to get things done"}/><div className="quick-action-grid">{quickActions.map(([icon,path,ar,en])=><button key={path} onClick={()=>navigate(`/${path}`)}><span><Icon name={icon}/></span><strong>{locale==="ar"?ar:en}</strong><small>{locale==="ar"?"فتح الآن":"Open now"}</small></button>)}</div></section>}
export function HomeCategories(){const{locale}=useStorefront();return <section className="home-section"><HomeHeading title={locale==="ar"?"تسوّق حسب القسم":"Shop by category"} subtitle={locale==="ar"?"أقسام مرنة لكل نوع من الخدمات الرقمية":"Flexible categories for every digital service"} path="/categories"/><div className="home-category-bento">{homeCategories.map((category,index)=><button className={index<2?"category-large":""} key={category.id} onClick={()=>navigate(`/categories/${category.slug}`)}><span className="category-art-home">{category.icon}</span><span><strong>{category.name[locale]}</strong><small>{category.description[locale]}</small><em>{category.count} {locale==="ar"?"منتج":"products"}</em></span><Icon name="arrow"/></button>)}</div></section>}
export function HomeProductCard({product,compact=false,favorite,onFavorite}:{product:HomeProduct;compact?:boolean;favorite:boolean;onFavorite:()=>void}){const{locale}=useStorefront();const status=product.availability==="available"?(locale==="ar"?"متاح":"Available"):product.availability==="limited"?(locale==="ar"?"محدود":"Limited"):(locale==="ar"?"غير متاح":"Unavailable");return <article className={`home-product-card ${compact?"compact":""}`}><button className="home-product-favorite" onClick={onFavorite} aria-label={t(locale,"favorites")} aria-pressed={favorite}><Icon name="heart" size={17}/></button>{product.discount&&<span className="home-discount">−{product.discount}%</span>}<button className={`home-product-visual variant-${product.visualVariant}`} onClick={()=>navigate(`/products/${product.slug}`)} aria-label={`${t(locale,"open")} ${product.title[locale]}`}><i/><b>{product.visualVariant.slice(0,2).toUpperCase()}</b><span>{product.categoryId.replace("-"," ")}</span></button><div className="home-product-body"><div className="home-product-meta"><span className={product.availability}>{status}</span><span>{product.executionType==="automatic"?(locale==="ar"?"تلقائي":"Automatic"):(locale==="ar"?"يدوي":"Manual")}</span></div><h3>{product.title[locale]}</h3><p>{product.subtitle[locale]}</p><div className="home-product-facts"><span><Icon name="check" size={13}/>{product.deliveryTime[locale]}</span><span>{product.popularity.toLocaleString("en-US")} {locale==="ar"?"طلب":"orders"}</span></div><div className="home-product-foot"><span><small>{locale==="ar"?"يبدأ من":"From"}</small><strong>${product.startingPrice.toFixed(2)}</strong>{product.oldPrice&&<del>${product.oldPrice.toFixed(2)}</del>}</span><button onClick={()=>navigate(`/products/${product.slug}`)} aria-label={t(locale,"open")}><Icon name="arrow"/></button></div></div></article>}
export function HomeProductRail({id,title,subtitle,items,favorites,toggle,compact=false}:{id?:string;title:string;subtitle:string;items:HomeProduct[];favorites:Set<string>;toggle:(id:string)=>void;compact?:boolean}){return <section id={id} className="home-section"><HomeHeading title={title} subtitle={subtitle} path="/categories"/><div className={`home-product-rail ${compact?"compact":""}`}>{items.map(product=><HomeProductCard key={product.id} product={product} compact={compact} favorite={favorites.has(product.id)} onFavorite={()=>toggle(product.id)}/>)}</div></section>}
export function HomeFeatured(){const{locale}=useStorefront();return <section className="home-featured"><div><span className="home-eyebrow">{locale==="ar"?"تشكيلة مختارة":"Featured collection"}</span><h2>{locale==="ar"?"وقت اللعب، من دون انتظار.":"Game time, without the wait."}</h2><p>{locale==="ar"?"باقات واضحة وتسليم رقمي منظم ضمن تجربة شراء واحدة.":"Clear packages and organized delivery in one purchase experience."}</p><button className="home-button light" onClick={()=>navigate("/categories/games")}>{locale==="ar"?"استكشف التشكيلة":"Explore collection"}</button></div><div className="featured-art" aria-hidden="true"><span>G/01</span><i/><b>FAST DELIVERY</b></div></section>}
export function HomeTrending(){const{locale}=useStorefront();return <section className="home-trending"><span>{locale==="ar"?"الأكثر طلبًا الآن":"Trending now"}</span><div>{[...homeProducts.slice(0,8),...homeProducts.slice(0,8)].map((product,index)=><button key={`${product.id}-${index}`} onClick={()=>navigate(`/products/${product.slug}`)}><i className={`variant-${product.visualVariant}`}/>{product.title[locale]}<small>${product.startingPrice.toFixed(2)}</small></button>)}</div></section>}
export function HomeOffers(){const{locale}=useStorefront();return <section className="home-section"><HomeHeading title={locale==="ar"?"عروض هذا الشهر":"This month's offers"} subtitle={locale==="ar"?"خصومات واضحة بتواريخ انتهاء حقيقية":"Clear discounts with real end dates"} path="/offers"/><div className="home-offers">{[{n:"18%",date:"2026-08-31",ar:"باقات ألعاب مختارة",en:"Selected game packs"},{n:"12%",date:"2026-09-15",ar:"اشتراكات سنوية",en:"Annual subscriptions"},{n:"$5",date:"2026-08-20",ar:"بطاقات رقمية",en:"Digital cards"}].map(offer=><article key={offer.en}><strong>{offer.n}</strong><span>{locale==="ar"?offer.ar:offer.en}</span><time dateTime={offer.date}>{locale==="ar"?"حتى":"Until"} {offer.date}</time><button onClick={()=>navigate("/offers")}><Icon name="arrow"/></button></article>)}</div></section>}
export function HomeWallet(){const{locale,state}=useStorefront();return <section className="home-wallet"><div><span>{locale==="ar"?"رصيد محفظتك":"Your wallet balance"}</span><strong>{money(state.balance,locale)}</strong><small>{locale==="ar"?"شراء أسرع من رصيد واحد واضح.":"Faster purchasing from one clear balance."}</small></div><div><button className="home-button light" onClick={()=>navigate("/wallet/deposit")}>{locale==="ar"?"إضافة رصيد":"Add funds"}</button><button className="home-button ghost-light" onClick={()=>navigate("/wallet")}>{locale==="ar"?"المعاملات":"Transactions"}</button></div></section>}
export function HomePayments(){const{locale}=useStorefront();return <section className="home-section payment-home"><HomeHeading title={locale==="ar"?"طرق إيداع مرنة":"Flexible deposit methods"} subtitle={locale==="ar"?"خيارات تجريبية يمكن تخصيصها لكل متجر":"Mock options configurable per storefront"} path="/wallet/deposit"/><div>{paymentMethods.map(method=><span key={method.en}><b>{method.icon}</b>{locale==="ar"?method.ar:method.en}</span>)}</div></section>}
export function HomeBenefits(){const{locale}=useStorefront();const rows=[["wallet","شراء من المحفظة","Wallet-first purchasing"],["bag","تتبع واضح للطلبات","Clear order tracking"],["shield","حساب وتجربة آمنة","Secure account experience"],["check","تسليم رقمي سريع","Fast digital delivery"]];return <section className="home-benefits">{rows.map(([icon,ar,en])=><article key={en}><span><Icon name={icon}/></span><h3>{locale==="ar"?ar:en}</h3><p>{locale==="ar"?"معلومات واضحة في كل خطوة من التجربة.":"Clear information at every step of the experience."}</p></article>)}</section>}
export function HomeSupport(){const{locale}=useStorefront();return <section className="home-support"><div><span className="home-eyebrow">{locale==="ar"?"دعم متصل بتجربتك":"Support connected to your experience"}</span><h2>{locale==="ar"?"هل تحتاج مساعدة قبل الشراء أو بعده؟":"Need help before or after purchase?"}</h2><p>{locale==="ar"?"ساعات العمل التجريبية 09:00–22:00 · إجابة منظمة ومتابعة واضحة.":"Mock hours 09:00–22:00 · Organized answers and clear follow-up."}</p></div><div><button className="home-button primary" onClick={()=>navigate("/support/new")}>{locale==="ar"?"فتح تذكرة":"Open ticket"}</button><button className="home-button ghost" onClick={()=>navigate("/support")}>{locale==="ar"?"الأسئلة الشائعة":"FAQs"}</button></div></section>}
export function HomeHeading({title,subtitle,path}:{title:string;subtitle:string;path?:string}){const{locale}=useStorefront();return <header className="home-section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{path&&<button onClick={()=>navigate(path)}>{t(locale,"viewAll")}<Icon name="arrow" size={16}/></button>}</header>}
export function HomeState({kind}:{kind:"skeleton"|"empty"|"error"|"offline"}){const{locale}=useStorefront();return <div className={`home-state ${kind}`} aria-live="polite">{kind==="skeleton"?<><i/><i/><i/></>:<><strong>{kind==="empty"?(locale==="ar"?"لا يوجد محتوى بعد":"Nothing here yet"):kind==="offline"?(locale==="ar"?"أنت غير متصل":"You're offline"):(locale==="ar"?"تعذر تحميل القسم":"Section unavailable")}</strong><small>{locale==="ar"?"يمكن المحاولة مرة أخرى لاحقًا.":"You can try again later."}</small></>}</div>}
