import { useMemo, useRef, useState } from "react";
import { homeCategories, homeProducts } from "../../data/home-data";
import { navigate } from "../../hooks/useRoute";
import { useStorefront } from "../../hooks/useStorefront";
import { Icon } from "../ui/Icon";

export function HomeSearch() {
  const { locale }=useStorefront(); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const root=useRef<HTMLDivElement>(null); const results=useMemo(()=>homeProducts.filter(p=>p.title[locale].toLowerCase().includes(query.toLowerCase())).slice(0,5),[query,locale]);
  return <section className="home-search-wrap" aria-label={locale==="ar"?"بحث ذكي":"Smart search"}><div ref={root} className={`home-search ${open?"is-open":""}`} onBlur={(event)=>{if(!root.current?.contains(event.relatedTarget))setOpen(false)}}><Icon name="search" size={22}/><label><span className="sr-only">{locale==="ar"?"ابحث في المتجر":"Search the store"}</span><input value={query} onFocus={()=>setOpen(true)} onChange={event=>{setQuery(event.target.value);setOpen(true)}} onKeyDown={event=>{if(event.key==="Escape")setOpen(false);if(event.key==="Enter"&&query)navigate(`/search?q=${encodeURIComponent(query)}`)}} placeholder={locale==="ar"?"ابحث عن منتج، قسم، أو خدمة رقمية...":"Search products, categories, or digital services..."}/></label>{query?<button className="search-clear" onClick={()=>setQuery("")} aria-label={locale==="ar"?"مسح":"Clear"}><Icon name="close" size={17}/></button>:<kbd>⌘ K</kbd>}{open&&<div className="home-search-panel"><div><span>{query?(locale==="ar"?"النتائج":"Results"):(locale==="ar"?"عمليات بحث شائعة":"Popular searches")}</span>{query?(results.length?results.map(product=><button key={product.id} onMouseDown={event=>event.preventDefault()} onClick={()=>navigate(`/products/${product.slug}`)}><i className={`mini-product ${product.visualVariant}`}/><strong>{product.title[locale]}</strong><small>${product.startingPrice.toFixed(2)}</small></button>):<p>{locale==="ar"?"لم نجد نتائج. جرّب عبارة أخرى.":"No results. Try another query."}</p>):["Gaming pass","Gift card","VPN","Subscriptions"].map(item=><button key={item} onMouseDown={event=>event.preventDefault()} onClick={()=>setQuery(item)}><Icon name="search" size={15}/><strong>{item}</strong></button>)}</div><div><span>{locale==="ar"?"الأقسام":"Categories"}</span>{homeCategories.slice(0,4).map(category=><button key={category.id} onMouseDown={event=>event.preventDefault()} onClick={()=>navigate(`/categories/${category.slug}`)}><b>{category.icon}</b><strong>{category.name[locale]}</strong></button>)}</div></div>}</div></section>;
}
