export const kpis=[
 {icon:"▣",ar:"المتاجر",en:"Stores",value:"248",change:"+12.4%",points:[18,24,21,30,34,31,42]},
 {icon:"◇",ar:"الشركات",en:"Companies",value:"86",change:"+8.1%",points:[16,19,18,25,23,29,33]},
 {icon:"▤",ar:"المنتجات",en:"Products",value:"12.8K",change:"+19.7%",points:[14,18,26,23,31,38,45]},
 {icon:"♙",ar:"المستخدمون",en:"Users",value:"34.2K",change:"+6.3%",points:[22,20,28,31,29,35,39]},
 {icon:"$",ar:"الإيرادات",en:"Revenue",value:"$284K",change:"+14.2%",points:[18,26,22,36,32,44,48]},
 {icon:"▥",ar:"الطلبات",en:"Orders",value:"9,842",change:"+11.8%",points:[20,25,32,28,39,41,47]},
 {icon:"✦",ar:"وكلاء AI",en:"AI Agents",value:"18",change:"+28.6%",points:[12,14,19,18,27,33,40]},
 {icon:"⇄",ar:"المزودون النشطون",en:"Active Providers",value:"12",change:"+4.2%",points:[24,24,28,27,31,33,35]},
] as const;
export const health=[{name:"API",ms:"42 ms",level:94},{name:"PostgreSQL",ms:"18 ms",level:97},{name:"Redis",ms:"9 ms",level:99},{name:"Queue",ms:"31 ms",level:92},{name:"Storage",ms:"63 ms",level:89},{name:"Scheduler",ms:"12 ms",level:98},{name:"Workers",ms:"27 ms",level:95},{name:"CPU",ms:"38%",level:62},{name:"RAM",ms:"61%",level:55},{name:"Disk",ms:"47%",level:70}] as const;
export const revenue:{[key:string]:number[]}={day:[18,32,27,44,39,58,65,61,76,82,79,91],week:[24,28,35,31,48,53,61,57,70,78,84,88],month:[15,21,29,37,34,49,57,64,69,77,85,93],year:[12,18,25,31,43,39,52,61,68,74,86,96]};
export const orders=[{ar:"قيد الانتظار",en:"Pending",value:328,total:1000,tone:"amber"},{ar:"قيد المعالجة",en:"Processing",value:542,total:1000,tone:"blue"},{ar:"مكتملة",en:"Completed",value:8240,total:9000,tone:"green"},{ar:"فاشلة",en:"Failed",value:86,total:1000,tone:"red"},{ar:"مستردة",en:"Refunded",value:41,total:1000,tone:"neutral"}] as const;
export const timeline=[{icon:"▣",ar:"تم إنشاء متجر Nova",en:"Nova store created",timeAr:"منذ 4 دقائق",timeEn:"4 minutes ago"},{icon:"◇",ar:"تم إنشاء شركة Vertex",en:"Vertex company created",timeAr:"منذ 18 دقيقة",timeEn:"18 minutes ago"},{icon:"⇄",ar:"تمت مزامنة المزود",en:"Provider synchronized",timeAr:"منذ 32 دقيقة",timeEn:"32 minutes ago"},{icon:"↗",ar:"اكتمل نشر Atlas",en:"Atlas deployment completed",timeAr:"منذ 48 دقيقة",timeEn:"48 minutes ago"},{icon:"↻",ar:"اكتملت النسخة الاحتياطية",en:"Backup completed",timeAr:"منذ ساعة",timeEn:"1 hour ago"},{icon:"✦",ar:"تم تنفيذ Workflow",en:"Workflow executed",timeAr:"منذ ساعتين",timeEn:"2 hours ago"},{icon:"✓",ar:"تم اعتماد العميل",en:"Customer approved",timeAr:"منذ 3 ساعات",timeEn:"3 hours ago"}] as const;
export const projects=[{name:"Nexus Commerce",statusAr:"نشط",statusEn:"Live",timeAr:"منذ 8 دقائق",timeEn:"8 min ago",members:["ON","LK","MS"]},{name:"Atlas Cloud",statusAr:"قيد النشر",statusEn:"Deploying",timeAr:"منذ 24 دقيقة",timeEn:"24 min ago",members:["YK","RN"]},{name:"Vertex Studio",statusAr:"مراجعة",statusEn:"Review",timeAr:"منذ ساعة",timeEn:"1 hour ago",members:["LN","SK","AM"]}] as const;
export const notices=[{tone:"critical",ar:"توقف Worker تجريبي",en:"Mock worker interruption",time:"09:42"},{tone:"warning",ar:"دومين سينتهي خلال 7 أيام",en:"Domain expires in 7 days",time:"09:18"},{tone:"info",ar:"تحديث مخطط للصيانة",en:"Scheduled maintenance update",time:"08:55"},{tone:"success",ar:"اكتملت مزامنة المزود",en:"Provider sync completed",time:"08:31"},{tone:"info",ar:"أضيف تقرير أسبوعي",en:"Weekly report added",time:"08:04"}] as const;
export const launches=[{icon:"▣",ar:"إنشاء متجر",en:"Create Store",target:"project-create"},{icon:"◇",ar:"إنشاء شركة",en:"Create Company",target:"action-add-company"},{icon:"▤",ar:"إنشاء منتج",en:"Create Product",target:"products"},{icon:"⇄",ar:"إضافة مزود",en:"Add Provider",target:"providers"},{icon:"⌘",ar:"Workflow جديد",en:"New Workflow",target:"action-create-workflow"},{icon:"✎",ar:"إنشاء Prompt",en:"Create Prompt",target:"action-add-prompt"},{icon:"↗",ar:"نشر",en:"Deploy",target:"deployments"},{icon:"↻",ar:"نسخة احتياطية",en:"Backup",target:"backups"},{icon:"♙",ar:"دعوة Admin",en:"Invite Admin",target:"users"},{icon:"≣",ar:"فتح السجلات",en:"Open Logs",target:"system-logs"}] as const;
