import { useEffect, useRef, useState, type ReactNode } from "react";
import { navigate } from "../../hooks/useRoute";
import { useStorefront } from "../../hooks/useStorefront";
import { money, t } from "../../utils/i18n";
import { storeConfig } from "../../data/store-data";
import { Icon } from "../ui/Icon";

const nav = [["/", "home"], ["/categories", "categories"], ["/offers", "offers"], ["/support", "support"]] as const;
export function StoreShell({ children, bare = false }: { children: ReactNode; bare?: boolean }) {
  const { locale, setLocale, theme, setTheme, state } = useStorefront(); const [menu, setMenu] = useState(false); const closeRef = useRef<HTMLButtonElement>(null); const unread = state.notices.filter(n => !n.read).length; const currentPath = window.location.pathname;
  const go = (path: string) => { setMenu(false); navigate(path); };
  useEffect(() => { if (!menu) return; closeRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setMenu(false); if (event.key === "Tab") { const drawer = document.querySelector<HTMLElement>(".mobile-drawer"); const focusable = drawer?.querySelectorAll<HTMLElement>("button"); if (!focusable?.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; addEventListener("keydown", onKey); return () => removeEventListener("keydown", onKey); }, [menu]);
  if (bare) return <div className="bare-shell"><button className="brand" onClick={() => go("/")}><span className="brand-mark">P</span><span>{storeConfig.name}</span></button>{children}</div>;
  return <div className="store-shell"><a className="skip-link" href="#main">{locale === "ar" ? "انتقل إلى المحتوى" : "Skip to content"}</a><div className="announcement"><span>{locale === "ar" ? "تسليم رقمي موثوق" : "Reliable digital delivery"}</span><button onClick={() => go("/offers")}>{locale === "ar" ? "اكتشف عروض الشهر ←" : "Explore this month's offers →"}</button></div>
    <header className="header"><button className="mobile-menu icon-button" onClick={() => setMenu(true)} aria-label={locale === "ar" ? "فتح القائمة" : "Open menu"} aria-expanded={menu}><Icon name="menu" /></button><button className="brand" onClick={() => go("/")}><span className="brand-mark">P</span><span>{storeConfig.name}</span></button>
      <nav className="main-nav" aria-label="Main navigation">{nav.map(([path, key]) => <button className={currentPath === path ? "active" : ""} key={path} onClick={() => go(path)}>{t(locale, key)}</button>)}</nav>
      <div className="header-actions"><button className="search-trigger" onClick={() => go("/search")}><Icon name="search" /><span>{t(locale, "search")}</span><kbd>⌘ K</kbd></button><button className="desktop-tool icon-button notification-button" onClick={() => go("/notifications")} aria-label={t(locale, "notifications")}><Icon name="bell" />{unread > 0 && <span className="badge">{unread}</span>}</button><button className="wallet-chip" onClick={() => go("/wallet")}><Icon name="wallet" /><span>{money(state.balance, locale)}</span></button><button className="desktop-tool icon-button" onClick={() => setLocale(locale === "ar" ? "en" : "ar")} aria-label="Language">{locale === "ar" ? "EN" : "ع"}</button><button className="desktop-tool icon-button" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} aria-label="Theme"><Icon name="sun" /></button><button className="avatar" onClick={() => go(state.loggedIn ? "/profile" : "/login")} aria-label={t(locale, "profile")}>JD</button></div>
    </header>{menu && <><button className="drawer-backdrop" aria-label={locale === "ar" ? "إغلاق القائمة" : "Close menu"} onClick={() => setMenu(false)} /><aside className="mobile-drawer" role="dialog" aria-modal="true" aria-label={locale === "ar" ? "قائمة المتجر" : "Store menu"}><div className="drawer-head"><span className="brand"><span className="brand-mark">P</span>{storeConfig.name}</span><button ref={closeRef} className="icon-button" onClick={() => setMenu(false)} aria-label={locale === "ar" ? "إغلاق" : "Close"}><Icon name="close" /></button></div><nav>{nav.map(([path,key]) => <button className={currentPath === path ? "active" : ""} key={path} onClick={() => go(path)}>{t(locale,key)}<Icon name="arrow" /></button>)}</nav><div className="drawer-account"><button onClick={() => go("/notifications")}><Icon name="bell" />{t(locale,"notifications")}<span>{unread}</span></button><button onClick={() => setLocale(locale === "ar" ? "en" : "ar")}><span className="drawer-glyph">文</span>{locale === "ar" ? "English" : "العربية"}</button><button onClick={() => setTheme(theme === "dark" ? "light" : "dark")}><Icon name="sun" />{locale === "ar" ? "تغيير المظهر" : "Switch appearance"}</button></div></aside></>}
    <main id="main" className="page-entry">{children}</main><Footer /><nav className="bottom-nav" aria-label="Mobile navigation">{[["/", "home", "home"], ["/categories", "grid", "categories"], ["/orders", "bag", "orders"], ["/wallet", "wallet", "wallet"], ["/profile", "user", "profile"]].map(([path, icon, key]) => <button className={currentPath === path || (path !== "/" && currentPath.startsWith(path)) ? "active" : ""} aria-current={currentPath === path ? "page" : undefined} key={path} onClick={() => go(path)}><Icon name={icon} /><span>{t(locale, key as Parameters<typeof t>[1])}</span></button>)}</nav></div>;
}
function Footer() { const { locale } = useStorefront(); return <footer className="footer"><div className="footer-brand"><span className="brand"><span className="brand-mark">P</span>{storeConfig.name}</span><p>{locale === "ar" ? "متجر خدمات رقمية واضح، سريع، ومصمم حول تجربة الشراء." : "A clear, fast digital service store built around the purchase experience."}</p><div className="social-placeholders"><button aria-label="Instagram">ig</button><button aria-label="X">x</button><button aria-label="Facebook">f</button></div></div><div><h3>{locale === "ar" ? "استكشف" : "Explore"}</h3><button onClick={() => navigate("/categories")}>{t(locale, "categories")}</button><button onClick={() => navigate("/offers")}>{t(locale, "offers")}</button><button onClick={() => navigate("/favorites")}>{t(locale,"favorites")}</button></div><div><h3>{locale === "ar" ? "المساعدة" : "Help"}</h3><button onClick={() => navigate("/support")}>{t(locale, "support")}</button><button onClick={() => navigate("/orders")}>{t(locale,"orders")}</button><button onClick={() => navigate("/about")}>{locale === "ar" ? "عن المتجر" : "About"}</button></div><div><h3>{locale === "ar" ? "قانوني" : "Legal"}</h3><button onClick={() => navigate("/terms")}>{locale === "ar" ? "الشروط" : "Terms"}</button><button onClick={() => navigate("/privacy")}>{locale === "ar" ? "الخصوصية" : "Privacy"}</button><span className="secure-note"><Icon name="shield" size={17} /> {locale === "ar" ? "تجربة شراء محمية" : "Protected checkout flow"}</span></div><div className="footer-bottom"><span>© 2026 {storeConfig.name}</span><span>{locale === "ar" ? "تجربة متجر تجريبية" : "Digital commerce storefront"}</span></div></footer>; }
