import { useCallback,useEffect,useRef,useState } from "react";

type SoundName="lampPull"|"lampOn"|"focus"|"press"|"digit"|"error"|"success"|"scanner"|"logout";
const SOUND_KEY="akatsuki-super-admin-preview-sound";

export function useAuthSounds(ambientActive=true) {
  const [enabled,setEnabled]=useState(()=>sessionStorage.getItem(SOUND_KEY)==="on");
  const contextRef=useRef<AudioContext|null>(null);const windRef=useRef<AudioBufferSourceNode|null>(null);const paperTimerRef=useRef<number|null>(null);
  const getContext=useCallback(()=>{const AudioContextClass=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioContextClass)return null;contextRef.current??=new AudioContextClass();return contextRef.current;},[]);
  const tone=useCallback((frequency:number,duration=.08,volume=.012,type:OscillatorType="sine",endFrequency?:number)=>{if(!enabled)return;const context=getContext();if(!context)return;void context.resume();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,context.currentTime);if(endFrequency)oscillator.frequency.exponentialRampToValueAtTime(endFrequency,context.currentTime+duration);gain.gain.setValueAtTime(volume,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+duration);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+duration);},[enabled,getContext]);
  const play=useCallback((name:SoundName)=>{const config:Record<SoundName,[number,number,number,OscillatorType,number?]>={lampPull:[125,.07,.008,"triangle",90],lampOn:[180,.22,.012,"sine",420],focus:[430,.045,.006,"sine"],press:[240,.045,.009,"triangle",190],digit:[590,.035,.006,"sine"],error:[155,.13,.016,"square",120],success:[430,.22,.012,"sine",820],scanner:[720,.1,.007,"triangle",480],logout:[210,.09,.008,"triangle",145]};tone(...config[name]);},[tone]);
  const toggle=useCallback(()=>{setEnabled(value=>{const next=!value;sessionStorage.setItem(SOUND_KEY,next?"on":"off");return next;});},[]);
  useEffect(()=>{if(!enabled){try{windRef.current?.stop();}catch{/* already stopped */}windRef.current=null;if(paperTimerRef.current)window.clearInterval(paperTimerRef.current);return;}const context=getContext();if(!context)return;void context.resume();const frames=context.sampleRate*2;const buffer=context.createBuffer(1,frames,context.sampleRate);const data=buffer.getChannelData(0);for(let index=0;index<frames;index++)data[index]=(Math.random()*2-1)*.22;const wind=context.createBufferSource();const filter=context.createBiquadFilter();const gain=context.createGain();wind.buffer=buffer;wind.loop=true;filter.type="lowpass";filter.frequency.value=260;gain.gain.value=ambientActive?.004:.00035;wind.connect(filter).connect(gain).connect(context.destination);wind.start();windRef.current=wind;if(ambientActive)paperTimerRef.current=window.setInterval(()=>tone(950,.055,.0025,"sine",620),6500);const visibility=()=>{if(document.hidden)void context.suspend();else void context.resume();};document.addEventListener("visibilitychange",visibility);return()=>{document.removeEventListener("visibilitychange",visibility);try{wind.stop();}catch{/* already stopped */}if(paperTimerRef.current)window.clearInterval(paperTimerRef.current);windRef.current=null;};},[ambientActive,enabled,getContext,tone]);
  return {enabled,toggle,play};
}
