import { useEffect,useState } from "react";
import { useAdminLocale } from "../../hooks/useAdminLocale";import { useAdminTheme } from "../../hooks/useAdminTheme";import { useAuthSounds } from "../../hooks/useAuthSounds";
import { getAdminItem,getParentGroup } from "../../navigation/admin-navigation";import DashboardOverview from "../dashboard/DashboardOverview";import PlaceholderPage from "../pages/PlaceholderPage";import ProjectDetails from "../project-factory/ProjectDetails";import ProjectFactoryList from "../project-factory/ProjectFactoryList";import ProjectWizard from "../project-factory/ProjectWizard";import QuickActionsHub from "../quick-actions/QuickActionsHub";import AdminSidebar from "./AdminSidebar";import AdminTopBar from "./AdminTopBar";
const COLLAPSE_KEY="akatsuki-super-admin-sidebar-collapsed";
export default function AdminShell({onLogout}:{onLogout:()=>void}){const [activeId,setActiveId]=useState("dashboard"),[expandedId,setExpandedId]=useState<string|null>(null),[collapsed,setCollapsed]=useState(()=>sessionStorage.getItem(COLLAPSE_KEY)==="true"),[mobileOpen,setMobileOpen]=useState(false);const {play}=useAuthSounds(),{theme,toggleTheme}=useAdminTheme(),{locale,dir,toggleLocale}=useAdminLocale(),activeItem=getAdminItem(activeId);
const navigate=(id:string)=>{setActiveId(id);const parent=getParentGroup(id);if(parent)setExpandedId(parent.id);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};const toggleCollapse=()=>setCollapsed(value=>{const next=!value;sessionStorage.setItem(COLLAPSE_KEY,String(next));return next}),logout=()=>{play("logout");onLogout()};
useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=dir;return()=>{document.documentElement.lang="ar";document.documentElement.dir="rtl"}},[locale,dir]);useEffect(()=>{document.body.style.overflow=mobileOpen?"hidden":"";const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setMobileOpen(false)};document.addEventListener("keydown",key);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",key)}},[mobileOpen]);
const content=activeId==="dashboard"?<DashboardOverview onNavigate={navigate} locale={locale}/>:activeId==="projects"||activeId==="drafts"?<ProjectFactoryList locale={locale} onNavigate={navigate}/>:activeId==="project-create"?<ProjectWizard locale={locale} onNavigate={navigate}/>:activeId.startsWith("project-detail:")?<ProjectDetails projectId={activeId.split(":")[1]} locale={locale} onNavigate={navigate}/>:<PlaceholderPage item={activeItem} locale={locale} onNavigate={navigate}/>,sidebarActiveId=activeId.startsWith("project-detail:")?"projects":activeId;
return <div className={`admin-app ${collapsed?"sidebar-collapsed":""}`} dir={dir} data-theme={theme} data-locale={locale}><AdminSidebar activeId={sidebarActiveId} expandedId={expandedId} collapsed={collapsed} mobileOpen={mobileOpen} locale={locale} onExpand={id=>setExpandedId(value=>value===id?null:id)} onNavigate={navigate} onCollapse={toggleCollapse} onClose={()=>setMobileOpen(false)}/><div className="admin-content"><AdminTopBar item={activeItem} locale={locale} theme={theme} onMenu={()=>setMobileOpen(true)} onNavigate={navigate} onLogout={logout} onTheme={toggleTheme} onLocale={toggleLocale}/><main className="admin-workspace">{content}</main></div><QuickActionsHub activeId={activeId} locale={locale} onNavigate={navigate}/></div>}
