import { useEffect,useRef,useState } from "react";
import type { AdminTheme } from "../../hooks/useAdminTheme";
import { pick,ui,type AdminLocale } from "../../localization/admin-translations";
import { mockSearchResults } from "../../mock-data";
import type { AdminNavItem } from "../../navigation/admin-navigation";
import AppIcon from "../ui/AppIcon";import LanguageToggle from "./LanguageToggle";import NotificationMenu from "./NotificationMenu";import ThemeToggle from "./ThemeToggle";import UserProfileMenu from "./UserProfileMenu";
export default function AdminTopBar({item,locale,theme,onMenu,onNavigate,onLogout,onTheme,onLocale}:{item:AdminNavItem;locale:AdminLocale;theme:AdminTheme;onMenu:()=>void;onNavigate:(id:string)=>void;onLogout:()=>void;onTheme:()=>void;onLocale:()=>void}){
 const [notifications,setNotifications]=useState(false),[profile,setProfile]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState("");const root=useRef<HTMLElement>(null),searchInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setNotifications(false);setProfile(false);setSearchOpen(false)}};const outside=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node)){setNotifications(false);setProfile(false);setSearchOpen(false)}};document.addEventListener("keydown",key);document.addEventListener("mousedown",outside);return()=>{document.removeEventListener("keydown",key);document.removeEventListener("mousedown",outside)}},[]);
 const results=mockSearchResults.filter(result=>!query||`${result.label} ${result.type}`.toLowerCase().includes(query.toLowerCase())).slice(0,5);const openSearch=()=>{setSearchOpen(true);requestAnimationFrame(()=>searchInput.current?.focus())};const subtitle=item.id==="dashboard"?(locale==="ar"?"مركز العمليات ومراقبة المنصة":"Platform operations and monitoring"):pick(item.description,locale);
 return <header className="admin-topbar" ref={root}><div className="topbar-title"><button className="mobile-menu-button" type="button" onClick={onMenu} aria-label={pick(ui.openMenu,locale)}><AppIcon name="menu"/></button><div key={`${item.id}-${locale}`}><h1>{pick(item.title,locale)}</h1><p>{subtitle}</p></div></div><div className="topbar-tools"><div className={`global-search ${searchOpen?"is-open":""}`}><button className="search-expand-button" type="button" aria-expanded={searchOpen} aria-label={pick(ui.search,locale)} onClick={()=>searchOpen?setSearchOpen(false):openSearch()}><AppIcon name="search"/></button><label aria-hidden={!searchOpen}><AppIcon name="search"/><input ref={searchInput} value={query} onChange={event=>setQuery(event.target.value)} placeholder={pick(ui.search,locale)} aria-label={pick(ui.search,locale)}/></label>{searchOpen&&query&&<div className="search-results">{results.length?results.map(result=><button type="button" onClick={()=>{onNavigate(result.target);setSearchOpen(false);setQuery("")}} key={result.label}><span>{result.type}</span><strong>{result.label}</strong></button>):<p>{pick(ui.noResults,locale)}</p>}</div>}</div><button className="quick-create" type="button" onClick={()=>onNavigate("create-account")}>{pick(ui.createAccount,locale)}</button><ThemeToggle theme={theme} locale={locale} onToggle={onTheme}/><LanguageToggle locale={locale} onToggle={onLocale}/><NotificationMenu open={notifications} locale={locale} onToggle={()=>{setNotifications(value=>!value);setProfile(false)}}/><UserProfileMenu open={profile} locale={locale} onToggle={()=>{setProfile(value=>!value);setNotifications(false)}} onNavigate={onNavigate} onLogout={onLogout}/></div></header>
}
