import { useEffect,useLayoutEffect,useRef,useState } from "react";
import { pick,ui,type AdminLocale } from "../../localization/admin-translations";
import { adminNavigation,dashboardItem,type AdminNavGroup } from "../../navigation/admin-navigation";
import AnimatedNavigationIndicator from "./AnimatedNavigationIndicator";
import AppIcon from "../ui/AppIcon";
export default function SidebarNavigation({activeId,expandedId,collapsed,locale,onExpand,onNavigate}:{activeId:string;expandedId:string|null;collapsed:boolean;locale:AdminLocale;onExpand:(id:string)=>void;onNavigate:(id:string)=>void}){
 const root=useRef<HTMLElement>(null);const nodes=useRef(new Map<string,HTMLButtonElement>());const [indicator,setIndicator]=useState({top:0,height:0,visible:false});
 const measure=()=>{const target=nodes.current.get(activeId);const nav=root.current;if(!target||!nav)return;const a=target.getBoundingClientRect(),b=nav.getBoundingClientRect();setIndicator({top:a.top-b.top+nav.scrollTop,height:a.height,visible:true});target.scrollIntoView({block:"nearest",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});};
 useLayoutEffect(measure,[activeId,expandedId,collapsed,locale]);useEffect(()=>{const observer=new ResizeObserver(measure);if(root.current)observer.observe(root.current);window.addEventListener("resize",measure);return()=>{observer.disconnect();window.removeEventListener("resize",measure);};},[activeId]);
 const bind=(id:string)=>(node:HTMLButtonElement|null)=>{if(node)nodes.current.set(id,node);else nodes.current.delete(id);};
 const iconFor=(id:string)=>id==="project-factory"?"projects":id==="clients"?"clients":id==="infrastructure"?"infrastructure":id==="commerce"?"commerce":id==="finance"?"finance":id==="support"?"support":id==="security"?"security":id==="system"?"system":"default";
 const group=(navGroup:AdminNavGroup)=>{const active=navGroup.items.some(entry=>entry.id===activeId),expanded=expandedId===navGroup.id;return <div className={`sidebar-group ${active?"has-active":""} ${expanded?"is-open":""}`} key={navGroup.id}><button className="group-trigger" type="button" title={collapsed?pick(navGroup.label,locale):undefined} aria-expanded={expanded} onClick={()=>onExpand(navGroup.id)}><i><AppIcon name={iconFor(navGroup.id)}/></i><span>{pick(navGroup.label,locale)}</span>{navGroup.id==="project-factory"&&<em>CORE</em>}<b>⌄</b></button><div className={`submenu ${expanded?"is-expanded":""}`}>{navGroup.items.map(entry=><button ref={bind(entry.id)} type="button" title={collapsed?pick(entry.label,locale):undefined} aria-current={entry.id===activeId?"page":undefined} className={entry.id===activeId?"active":""} onClick={()=>onNavigate(entry.id)} key={entry.id}><i><AppIcon name={iconFor(navGroup.id)}/></i><span>{pick(entry.label,locale)}</span></button>)}</div></div>};
 return <nav ref={root} className="sidebar-navigation" aria-label={pick(ui.admin,locale)}><AnimatedNavigationIndicator {...indicator}/><div className="sidebar-section-label">{locale==="ar"?"مركز القيادة":"COMMAND CENTER"}</div><button ref={bind(dashboardItem.id)} type="button" title={collapsed?pick(dashboardItem.label,locale):undefined} aria-current={activeId===dashboardItem.id?"page":undefined} className={`standalone-nav ${activeId===dashboardItem.id?"active":""}`} onClick={()=>onNavigate(dashboardItem.id)}><i><AppIcon name="dashboard"/></i><span>{pick(dashboardItem.label,locale)}</span></button><div className="sidebar-section-label">{locale==="ar"?"المشاريع والعمليات":"PROJECTS & OPERATIONS"}</div>{adminNavigation.map(group)}</nav>
}
