import { text,type LocalizedText } from "../localization/admin-translations";
export interface AdminNavItem{id:string;label:LocalizedText;icon:string;title:LocalizedText;breadcrumb:LocalizedText[];description:LocalizedText;action?:LocalizedText}
export interface AdminNavGroup{id:string;label:LocalizedText;icon:string;items:AdminNavItem[]}
const dashboardLabel=text("لوحة التحكم","Dashboard");
const item=(id:string,ar:string,en:string,icon:string,group:LocalizedText,description:LocalizedText,action?:LocalizedText):AdminNavItem=>({id,label:text(ar,en),icon,title:text(ar,en),breadcrumb:[dashboardLabel,group,text(ar,en)],description,action});
export const dashboardItem:AdminNavItem={id:"dashboard",label:dashboardLabel,icon:"⌂",title:dashboardLabel,breadcrumb:[dashboardLabel],description:text("نظرة عامة مختصرة على عمليات المنصة.","A concise overview of platform operations.")};
const g=(id:string,ar:string,en:string,icon:string,rows:Array<[string,string,string,string,LocalizedText,LocalizedText?]>):AdminNavGroup=>{const label=text(ar,en);return{id,label,icon,items:rows.map(([key,a,e,i,d,action])=>item(key,a,e,i,label,d,action))};};
export const adminNavigation:AdminNavGroup[]=[
g("project-factory","مصنع المشاريع","Project Factory","◫",[["project-create","إنشاء مشروع جديد","Create Project","＋",text("بدء مشروع عميل جديد ضمن سير عمل منظم.","Start a client project in a structured workflow."),text("إنشاء مشروع","Create Project")],["projects","جميع المشاريع","All Projects","▦",text("عرض مشاريع العملاء وحالاتها الحالية.","View client projects and their status.")],["drafts","المسودات","Drafts","◱",text("مراجعة المشاريع المحفوظة قبل الإطلاق.","Review saved projects before launch.")],["templates","القوالب","Templates","▧",text("إدارة قوالب الانطلاق المعتمدة للمشاريع.","Manage approved project templates.")],["deployments","عمليات النشر","Deployments","↗",text("متابعة عمليات نشر المشاريع وحالاتها.","Track project deployments.")]]),
g("clients","العملاء","Clients","◇",[["clients","العملاء","Clients","◇",text("إدارة ملفات العملاء وعلاقاتهم بالمشاريع.","Manage client profiles and projects."),text("إضافة عميل","Add Client")]]),
g("infrastructure","البنية التحتية","Infrastructure","⌘",[["hosting","الاستضافات","Hosting","▣",text("إدارة استضافات مشاريع العملاء.","Manage client project hosting.")],["domains","الدومينات","Domains","◎",text("متابعة الدومينات وتواريخ الانتهاء.","Track domains and expiry dates.")],["databases","قواعد البيانات","Databases","◉",text("عرض حدود قواعد البيانات المستقبلية.","View future database boundaries.")],["backups","النسخ الاحتياطي","Backups","↻",text("متابعة سياسات النسخ والاستعادة.","Track backup and recovery policies.")]]),
g("commerce","التجارة والخدمات","Commerce & Services","◆",[["products","المنتجات والخدمات","Products & Services","▤",text("إدارة كتالوج الخدمات والمنتجات.","Manage the products and services catalog.")],["providers","مزودو الخدمات","Providers","⇄",text("متابعة مزودي التنفيذ واتصالاتهم.","Track service providers and connections.")],["orders","الطلبات","Orders","▥",text("عرض الطلبات وحالات التنفيذ.","View orders and fulfillment status.")],["payments","المدفوعات","Payments","◈",text("متابعة عمليات الدفع وحالاتها.","Track payments and their status.")]]),
g("finance","الخطط والمحاسبة","Plans & Finance","▨",[["plans","الخطط والاشتراكات","Plans & Subscriptions","▦",text("إدارة الخطط واشتراكات العملاء.","Manage plans and subscriptions.")],["invoices","الفواتير","Invoices","▤",text("متابعة فواتير المنصة.","Track platform invoices.")],["income-expenses","الإيرادات والمصاريف","Income & Expenses","↕",text("عرض حدود الإيرادات والمصاريف.","View income and expense boundaries.")],["financial-reports","التقارير المالية","Financial Reports","◫",text("تجميع التقارير المالية.","Compile financial reports.")]]),
g("support","الدعم والجودة","Support & Quality","◍",[["tickets","تذاكر الدعم","Support Tickets","◌",text("متابعة تذاكر دعم العملاء.","Track client support tickets.")],["change-requests","طلبات التعديل","Change Requests","✎",text("إدارة طلبات تعديل المشاريع.","Manage project change requests.")],["incidents","الأعطال","Incidents","⚠",text("توثيق الأعطال ومتابعتها.","Document and track incidents.")]]),
g("security","الأمان والصلاحيات","Security & Access","◒",[["users","المستخدمون","Users","♙",text("إدارة مستخدمي الإدارة.","Manage administration users.")],["roles","الأدوار والصلاحيات","Roles & Permissions","⌾",text("تنظيم الأدوار والصلاحيات.","Organize roles and permissions.")],["sessions","جلسات الدخول","Sessions","◴",text("مراجعة جلسات الدخول.","Review sign-in sessions.")],["audit-log","سجل العمليات","Audit Log","≡",text("مراجعة سجل العمليات.","Review the audit log.")]]),
g("system","النظام","System","⚙",[["system-health","حالة النظام","System Health","◉",text("عرض مؤشرات حالة النظام.","View system health indicators.")],["system-logs","السجلات","Logs","≣",text("مراجعة سجلات التشغيل.","Review operational logs.")],["integrations","التكاملات","Integrations","⌁",text("إدارة حدود التكاملات.","Manage integration boundaries.")],["general-settings","الإعدادات العامة","General Settings","⚙",text("تهيئة إعدادات المنصة.","Configure platform settings.")]]),
];
export const createAccountItem:AdminNavItem={id:"create-account",label:text("إنشاء حساب","Create Account"),icon:"＋",title:text("إنشاء حساب","Create Account"),breadcrumb:[dashboardLabel,text("إنشاء حساب","Create Account")],description:text("مساحة مخصصة لإنشاء حساب إداري جديد بعد اعتماد النموذج والصلاحيات.","A future workspace for creating an administrative account after the form and permissions are approved."),action:text("العودة إلى لوحة التحكم","Return to Dashboard")};
export const allAdminItems=[dashboardItem,createAccountItem,...adminNavigation.flatMap(group=>group.items)];
export const getAdminItem=(id:string)=>allAdminItems.find(entry=>entry.id===id)??dashboardItem;
export const getParentGroup=(id:string)=>adminNavigation.find(group=>group.items.some(entry=>entry.id===id));
